const CONFIG = {
  SHEET_ID: "1ycEByJaa3fBdx19SMqg6KPCKQSt9VEOqlJFJo5eg1D0",
  ABA_LANCAMENTOS: "LANÇAMENTOS",
  PASTA_RAIZ: "Financeiro",
  LABEL_ENTRADA: "FINANCEIRO/ENTRADA",
  LABEL_PROCESSADO: "FINANCEIRO/PROCESSADO"
};
